### PR TITLE
Cashew cmake

### PR DESCRIPTION
**Pull request by nickdesaulniers**
review? @kripken

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
ah, bad fork, let me fix this up

**Comment by nickdesaulniers** [comment]
ok good to go

**Comment by kripken** [comment]
The upstream for this is https://github.com/kripken/cashew , can you please make a pull to there?

Initial note: is cmake 3 needed? e.g. my machine here has only 2.8.12.2.

**Comment by nickdesaulniers** [comment]
probably not, can you test out the patch upstream, and modify the version from 3.0 to 2.8 and test?

Closing this PR.  Will issue a new one updating the version here after merging upstream.

**Pull request closed without merging**
